### ISSUE TITLE
Instaloader HTTP error code 401

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [ggogel/SocialMediaDownloadMaubot#10]
```
Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mautrix/client/syncer.py", line 236, in _catch_errors
    await handler(data)
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/socialmediadownload.py", line 58, in on_message
    await self.handle_instagram(evt, url_tup)
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/socialmediadownload.py", line 188, in handle_instagram
    post = instaloader.Post.from_shortcode(L.context, shortcode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
                 ^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 324, in _full_metadata
    self._obtain_metadata()
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 311, in _obtain_metadata
    pic_json = self._context.graphql_query(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 474, in graphql_query
    resp_json = self.get_json('graphql/query',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 439, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 439, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 429, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.
```

**Comment by ggogel** [comment]
This is not a bug. Error 401 means you're blocked. This is usually due to the IP address. They generally block all datacenter IPs. If there are too many requests from a residential IP, they'll also ban it for some time.

**Comment by ggogel** [comment]
I'll leave this issue open for now. This is not a bug, but Instagram's recently added stricter blocking of anonymous access causes it.

For reference the numerous issues on the Instaloader repository:
https://github.com/instaloader/instaloader/issues/2011
https://github.com/instaloader/instaloader/issues/2319
https://github.com/instaloader/instaloader/issues/2400

**Comment by ggogel** [comment]
I’ve released a new version that includes an updated Instaloader, as referenced in [this GitHub comment](https://github.com/instaloader/instaloader/issues/2400#issuecomment-2423416379).

Currently, everything is functioning smoothly. However, it may only be a matter of time before this method is blocked.
